name: publish jsons to Administrativ_grense/Territorialområde/Fastlands-Norge & tif to punkt-oppslag

on:
  push:
    branches: [ deployment ]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps: 
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm update
      - run: npm run download
      - run: npm run transform
